// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;
export function GetSystemResources():Promise<any>;
export function OpenLogFile(arg1:string):Promise<boolean>;
export function FetchDockerHubPopular():Promise<any>;
export function SearchDockerHub(arg1:string):Promise<any>;
export function FetchDockerHubTags(arg1:string):Promise<any>;
export function WriteLog(arg1:string, arg2:string, arg3:string):Promise<void>;
export function GetSetting(arg1:string):Promise<string>;
