// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateAppHeight(arg1) {
  return window['go']['main']['App']['CalculateAppHeight'](arg1);
}

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ExportProjectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportProjectFile'](arg1, arg2, arg3);
}

export function GenerateYaml(arg1, arg2) {
  return window['go']['main']['App']['GenerateYaml'](arg1, arg2);
}

export function GetHistoryLogs() {
  return window['go']['main']['App']['GetHistoryLogs']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetSystemResources() {
  return window['go']['main']['App']['GetSystemResources']();
}

export function GetTargetScreen(arg1) {
  return window['go']['main']['App']['GetTargetScreen'](arg1);
}

export function GetTargetScreenHeight(arg1) {
  return window['go']['main']['App']['GetTargetScreenHeight'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportProjectFile() {
  return window['go']['main']['App']['ImportProjectFile']();
}

export function JumpToHistory(arg1) {
  return window['go']['main']['App']['JumpToHistory'](arg1);
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function PushHistory(arg1) {
  return window['go']['main']['App']['PushHistory'](arg1);
}

export function Redo() {
  return window['go']['main']['App']['Redo']();
}

export function SaveProject(arg1, arg2) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2);
}

export function SaveSetting(arg1, arg2) {
  return window['go']['main']['App']['SaveSetting'](arg1, arg2);
}

export function SetInitialFile(arg1) {
  return window['go']['main']['App']['SetInitialFile'](arg1);
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}

export function UpdateProject(arg1, arg2) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2);
}
