// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function CloseWindow():Promise<void>;

export function DeleteProject(arg1:number):Promise<boolean>;

export function ExportProjectFile(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function GetHistoryLogs():Promise<Array<db.HistoryLog>>;

export function GetProjects():Promise<Array<db.Project>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSystemResources():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function ImportProjectFile():Promise<string>;

export function JumpToHistory(arg1:number):Promise<string>;

export function LoadProject(arg1:number):Promise<db.Project>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function PushHistory(arg1:string):Promise<void>;

export function Redo():Promise<string>;

export function SaveProject(arg1:string,arg2:string):Promise<number>;

export function SaveSetting(arg1:string,arg2:string):Promise<boolean>;

export function SetInitialFile(arg1:string):Promise<void>;

export function Undo():Promise<string>;

export function UpdateProject(arg1:number,arg2:string):Promise<boolean>;
